In [1]:
from pathlib import Path

from eyened_orm.importer.importer import Importer
from eyened_orm.importer.importer_dtos import PatientImport, StudyImport, SeriesImport, ImageImport
from eyened_orm import Database

In [2]:
from dotenv import load_dotenv
env_path = Path.cwd().parent.parent / ".env.dev"
load_dotenv(env_path)

session = Database().create_session()

In [3]:
# Set up project information
project_name = "FAU Fundus Dataset"
extract_dir = Path("/mnt/oogergo/eyened/public_data/av_segmentation/HRF_AV")
# Get all image paths
images_dir = extract_dir / "images"
image_paths = list(images_dir.glob("*"))

print(f"Found {len(image_paths)} images.")

Found 45 images.

In [4]:
storage_backends = {
    "/mnt/oogergo/": "oogergo",
}

def split_path(path):
    for key, value in storage_backends.items():
        if str(path).startswith(key):
            return value, str(path)[len(key) :]
    raise ValueError(f"Path {path} not found in storage backends")

def get_image_import(img_path):
    storage_backend_key, object_key = split_path(img_path)
    return ImageImport(object_key=object_key, storage_backend_key=storage_backend_key)

In [5]:
# The dataset has images named as g0001.jpg, g0002.jpg, etc.
# Let's group images together in batches to demonstrate the hierarchy

# Create the data structure for the Importer
# Even though in this dataset each image is of a different patient
# We'll create one "patient" for every 10 images as an example
from datetime import date


data = []
batch_size = 10

for i in range(0, len(image_paths), batch_size):
    batch_images = image_paths[i : i + batch_size]

    # Create image objects
    images = [get_image_import(img_path) for img_path in batch_images]

    # Create hierarchy objects
    series = SeriesImport(images=images)
    study = StudyImport(study_date=date.today(), series=[series])

    patient_item = PatientImport(
        project_name=project_name,
        patient_identifier=f"Patient_{i // batch_size + 1}",
        studies=[study],
    )

    data.append(patient_item)

print(f"Created data structure with {len(data)} patients.")
print(f"First patient has {len(data[0].studies[0].series[0].images)} images.")

Created data structure with 5 patients.
First patient has 10 images.

### Summaries

The summary method will return a summary of created ORM objects without writing anything to the database

In [6]:
# We need to specify create_patients=True, create_studies=True
# since we're not providing identifiers
importer = Importer(
    session=session,
    create_projects=True,
    create_patients=True,
    create_studies=True,
    run_ai_models=False, 
    generate_thumbnails=True,
)

# Display a summary of what will be imported
import_summary = importer.import_many(data, summary=True)

Import Summary for Projects: FAU Fundus Dataset
----------------  Object Statistics  ----------------
        Entity  Total  New  Existing New_Percentage Existing_Percentage
 ImageInstance     45   45         0         100.0%                0.0%
       Project      1    0         1           0.0%              100.0%
       Patient      5    5         0         100.0%                0.0%
   DeviceModel      1    0         1           0.0%              100.0%
StorageBackend      1    0         1           0.0%              100.0%
  ImageStorage     45   45         0         100.0%                0.0%
         Study      5    5         0         100.0%                0.0%
DeviceInstance      1    0         1           0.0%              100.0%
        Series      5    5         0         100.0%                0.0%

-----------  Column Population Statistics  -----------
- only for new entities
- values set to NULL are not considered populated

Populated ImageInstance Columns:
           Column  Populated Percentage
DatasetIdentifier         45     100.0%
     DateInserted         45     100.0%
         Inactive         45     100.0%

Populated Patient Columns:
           Column  Populated Percentage
     DateInserted          5     100.0%
PatientIdentifier          5     100.0%

Populated ImageStorage Columns:
   Column  Populated Percentage
   Format         45     100.0%
IsPrimary         45     100.0%
ObjectKey         45     100.0%

Populated Study Columns:
      Column  Populated Percentage
DateInserted          5     100.0%
   StudyDate          5     100.0%

### Execution

Once satisfied with the summary, commit the import to the database with `importer.exec`
There might still be Exceptions generated during import, in which case nothing will change in the DB and no files will be written.

Post-insertion scripts will run after insertion for non-essential steps such as:

- Thumbnail generation (highly recommended to run)
- Running image preprocessing scripts (eg. CFI bounds detection)
- Running AI models which populate DB columns
- Hashing the files for error and duplicate checks

In [7]:
importer.import_many(data)

[ImageInstance(ImageInstanceID=56, PublicID=16w5xxw8, SeriesID=7, SourceInfoID=None, DeviceInstanceID=2, ModalityID=None, ScanID=None, Modality=None, SOPInstanceUid=None, SOPClassUid=None, PhotometricInterpretation=None, SamplesPerPixel=None, Rows_y=None, Columns_x=None, NrOfFrames=None, SliceThickness=None, ResolutionAxial=None, ResolutionHorizontal=None, ResolutionVertical=None, HorizontalFieldOfView=None, Laterality=None, DICOMModality=None, AnatomicRegion=None, ETDRSField=None, Angiography=None, AcquisitionDateTime=None, PupilDilated=None, DatasetIdentifier=, AltDatasetIdentifier=None, ThumbnailPath=None, OldPath=None, FDAIdentifier=None, Inactive=False, CFROI=None, CFKeypoints=None, CFQuality=None, DateInserted=2026-03-11 11:51:16, DateModified=None, DatePreprocessed=None),
 ImageInstance(ImageInstanceID=67, PublicID=cm4rmvtw, SeriesID=8, SourceInfoID=None, DeviceInstanceID=2, ModalityID=None, ScanID=None, Modality=None, SOPInstanceUid=None, SOPClassUid=None, PhotometricInterpretation=None, SamplesPerPixel=None, Rows_y=None, Columns_x=None, NrOfFrames=None, SliceThickness=None, ResolutionAxial=None, ResolutionHorizontal=None, ResolutionVertical=None, HorizontalFieldOfView=None, Laterality=None, DICOMModality=None, AnatomicRegion=None, ETDRSField=None, Angiography=None, AcquisitionDateTime=None, PupilDilated=None, DatasetIdentifier=, AltDatasetIdentifier=None, ThumbnailPath=None, OldPath=None, FDAIdentifier=None, Inactive=False, CFROI=None, CFKeypoints=None, CFQuality=None, DateInserted=2026-03-11 11:51:16, DateModified=None, DatePreprocessed=None),
 ImageInstance(ImageInstanceID=75, PublicID=f2sifd6y, SeriesID=8, SourceInfoID=None, DeviceInstanceID=2, ModalityID=None, ScanID=None, Modality=None, SOPInstanceUid=None, SOPClassUid=None, PhotometricInterpretation=None, SamplesPerPixel=None, Rows_y=None, Columns_x=None, NrOfFrames=None, SliceThickness=None, ResolutionAxial=None, ResolutionHorizontal=None, ResolutionVertical=None, HorizontalFieldOfView=None, Laterality=None, DICOMModality=None, AnatomicRegion=None, ETDRSField=None, Angiography=None, AcquisitionDateTime=None, PupilDilated=None, DatasetIdentifier=, AltDatasetIdentifier=None, ThumbnailPath=None, OldPath=None, FDAIdentifier=None, Inactive=False, CFROI=None, CFKeypoints=None, CFQuality=None, DateInserted=2026-03-11 11:51:16, DateModified=None, DatePreprocessed=None),
 ImageInstance(ImageInstanceID=82, PublicID=a73gedyj, SeriesID=9, SourceInfoID=None, DeviceInstanceID=2, ModalityID=None, ScanID=None, Modality=None, SOPInstanceUid=None, SOPClassUid=None, PhotometricInterpretation=None, SamplesPerPixel=None, Rows_y=None, Columns_x=None, NrOfFrames=None, SliceThickness=None, ResolutionAxial=None, ResolutionHorizontal=None, ResolutionVertical=None, HorizontalFieldOfView=None, Laterality=None, DICOMModality=None, AnatomicRegion=None, ETDRSField=None, Angiography=None, AcquisitionDateTime=None, PupilDilated=None, DatasetIdentifier=, AltDatasetIdentifier=None, ThumbnailPath=None, OldPath=None, FDAIdentifier=None, Inactive=False, CFROI=None, CFKeypoints=None, CFQuality=None, DateInserted=2026-03-11 11:51:16, DateModified=None, DatePreprocessed=None),
 ImageInstance(ImageInstanceID=84, PublicID=qohz8ih1, SeriesID=9, SourceInfoID=None, DeviceInstanceID=2, ModalityID=None, ScanID=None, Modality=None, SOPInstanceUid=None, SOPClassUid=None, PhotometricInterpretation=None, SamplesPerPixel=None, Rows_y=None, Columns_x=None, NrOfFrames=None, SliceThickness=None, ResolutionAxial=None, ResolutionHorizontal=None, ResolutionVertical=None, HorizontalFieldOfView=None, Laterality=None, DICOMModality=None, AnatomicRegion=None, ETDRSField=None, Angiography=None, AcquisitionDateTime=None, PupilDilated=None, DatasetIdentifier=, AltDatasetIdentifier=None, ThumbnailPath=None, OldPath=None, FDAIdentifier=None, Inactive=False, CFROI=None, CFKeypoints=None, CFQuality=None, DateInserted=2026-03-11 11:51:16, DateModified=None, DatePreprocessed=None),
 ImageInstance(ImageInstanceID=78, PublicID=xu78u8pa, SeriesID=9, SourceInfoID=None, DeviceInstanceID=2, ModalityID=None, ScanID=None, Modality=None, SOPInstanceUid=None, SOPClassUid=None, PhotometricInterpretation=None, SamplesPerPixel=None, Rows_y=None, Columns_x=None, NrOfFrames=None, SliceThickness=None, ResolutionAxial=None, ResolutionHorizontal=None, ResolutionVertical=None, HorizontalFieldOfView=None, Laterality=None, DICOMModality=None, AnatomicRegion=None, ETDRSField=None, Angiography=None, AcquisitionDateTime=None, PupilDilated=None, DatasetIdentifier=, AltDatasetIdentifier=None, ThumbnailPath=None, OldPath=None, FDAIdentifier=None, Inactive=False, CFROI=None, CFKeypoints=None, CFQuality=None, DateInserted=2026-03-11 11:51:16, DateModified=None, DatePreprocessed=None),
 ImageInstance(ImageInstanceID=65, PublicID=fs2x5pmi, SeriesID=7, SourceInfoID=None, DeviceInstanceID=2, ModalityID=None, ScanID=None, Modality=None, SOPInstanceUid=None, SOPClassUid=None, PhotometricInterpretation=None, SamplesPerPixel=None, Rows_y=None, Columns_x=None, NrOfFrames=None, SliceThickness=None, ResolutionAxial=None, ResolutionHorizontal=None, ResolutionVertical=None, HorizontalFieldOfView=None, Laterality=None, DICOMModality=None, AnatomicRegion=None, ETDRSField=None, Angiography=None, AcquisitionDateTime=None, PupilDilated=None, DatasetIdentifier=, AltDatasetIdentifier=None, ThumbnailPath=None, OldPath=None, FDAIdentifier=None, Inactive=False, CFROI=None, CFKeypoints=None, CFQuality=None, DateInserted=2026-03-11 11:51:16, DateModified=None, DatePreprocessed=None),
 ImageInstance(ImageInstanceID=77, PublicID=6z29u67q, SeriesID=9, SourceInfoID=None, DeviceInstanceID=2, ModalityID=None, ScanID=None, Modality=None, SOPInstanceUid=None, SOPClassUid=None, PhotometricInterpretation=None, SamplesPerPixel=None, Rows_y=None, Columns_x=None, NrOfFrames=None, SliceThickness=None, ResolutionAxial=None, ResolutionHorizontal=None, ResolutionVertical=None, HorizontalFieldOfView=None, Laterality=None, DICOMModality=None, AnatomicRegion=None, ETDRSField=None, Angiography=None, AcquisitionDateTime=None, PupilDilated=None, DatasetIdentifier=, AltDatasetIdentifier=None, ThumbnailPath=None, OldPath=None, FDAIdentifier=None, Inactive=False, CFROI=None, CFKeypoints=None, CFQuality=None, DateInserted=2026-03-11 11:51:16, DateModified=None, DatePreprocessed=None),
 ImageInstance(ImageInstanceID=69, PublicID=zynmcdin, SeriesID=8, SourceInfoID=None, DeviceInstanceID=2, ModalityID=None, ScanID=None, Modality=None, SOPInstanceUid=None, SOPClassUid=None, PhotometricInterpretation=None, SamplesPerPixel=None, Rows_y=None, Columns_x=None, NrOfFrames=None, SliceThickness=None, ResolutionAxial=None, ResolutionHorizontal=None, ResolutionVertical=None, HorizontalFieldOfView=None, Laterality=None, DICOMModality=None, AnatomicRegion=None, ETDRSField=None, Angiography=None, AcquisitionDateTime=None, PupilDilated=None, DatasetIdentifier=, AltDatasetIdentifier=None, ThumbnailPath=None, OldPath=None, FDAIdentifier=None, Inactive=False, CFROI=None, CFKeypoints=None, CFQuality=None, DateInserted=2026-03-11 11:51:16, DateModified=None, DatePreprocessed=None),
 ImageInstance(ImageInstanceID=68, PublicID=xoke4nlw, SeriesID=8, SourceInfoID=None, DeviceInstanceID=2, ModalityID=None, ScanID=None, Modality=None, SOPInstanceUid=None, SOPClassUid=None, PhotometricInterpretation=None, SamplesPerPixel=None, Rows_y=None, Columns_x=None, NrOfFrames=None, SliceThickness=None, ResolutionAxial=None, ResolutionHorizontal=None, ResolutionVertical=None, HorizontalFieldOfView=None, Laterality=None, DICOMModality=None, AnatomicRegion=None, ETDRSField=None, Angiography=None, AcquisitionDateTime=None, PupilDilated=None, DatasetIdentifier=, AltDatasetIdentifier=None, ThumbnailPath=None, OldPath=None, FDAIdentifier=None, Inactive=False, CFROI=None, CFKeypoints=None, CFQuality=None, DateInserted=2026-03-11 11:51:16, DateModified=None, DatePreprocessed=None),
 ImageInstance(ImageInstanceID=46, PublicID=s0hiq4kt, SeriesID=6, SourceInfoID=None, DeviceInstanceID=2, ModalityID=None, ScanID=None, Modality=None, SOPInstanceUid=None, SOPClassUid=None, PhotometricInterpretation=None, SamplesPerPixel=None, Rows_y=None, Columns_x=None, NrOfFrames=None, SliceThickness=None, ResolutionAxial=None, ResolutionHorizontal=None, ResolutionVertical=None, HorizontalFieldOfView=None, Laterality=None, DICOMModality=None, AnatomicRegion=None, ETDRSField=None, Angiography=None, AcquisitionDateTime=None, PupilDilated=None, DatasetIdentifier=, AltDatasetIdentifier=None, ThumbnailPath=None, OldPath=None, FDAIdentifier=None, Inactive=False, CFROI=None, CFKeypoints=None, CFQuality=None, DateInserted=2026-03-11 11:51:16, DateModified=None, DatePreprocessed=None),
 ImageInstance(ImageInstanceID=61, PublicID=4my8v6i3, SeriesID=7, SourceInfoID=None, DeviceInstanceID=2, ModalityID=None, ScanID=None, Modality=None, SOPInstanceUid=None, SOPClassUid=None, PhotometricInterpretation=None, SamplesPerPixel=None, Rows_y=None, Columns_x=None, NrOfFrames=None, SliceThickness=None, ResolutionAxial=None, ResolutionHorizontal=None, ResolutionVertical=None, HorizontalFieldOfView=None, Laterality=None, DICOMModality=None, AnatomicRegion=None, ETDRSField=None, Angiography=None, AcquisitionDateTime=None, PupilDilated=None, DatasetIdentifier=, AltDatasetIdentifier=None, ThumbnailPath=None, OldPath=None, FDAIdentifier=None, Inactive=False, CFROI=None, CFKeypoints=None, CFQuality=None, DateInserted=2026-03-11 11:51:16, DateModified=None, DatePreprocessed=None),
 ImageInstance(ImageInstanceID=79, PublicID=zsjq1m7q, SeriesID=9, SourceInfoID=None, DeviceInstanceID=2, ModalityID=None, ScanID=None, Modality=None, SOPInstanceUid=None, SOPClassUid=None, PhotometricInterpretation=None, SamplesPerPixel=None, Rows_y=None, Columns_x=None, NrOfFrames=None, SliceThickness=None, ResolutionAxial=None, ResolutionHorizontal=None, ResolutionVertical=None, HorizontalFieldOfView=None, Laterality=None, DICOMModality=None, AnatomicRegion=None, ETDRSField=None, Angiography=None, AcquisitionDateTime=None, PupilDilated=None, DatasetIdentifier=, AltDatasetIdentifier=None, ThumbnailPath=None, OldPath=None, FDAIdentifier=None, Inactive=False, CFROI=None, CFKeypoints=None, CFQuality=None, DateInserted=2026-03-11 11:51:16, DateModified=None, DatePreprocessed=None),
 ImageInstance(ImageInstanceID=72, PublicID=6eksiky5, SeriesID=8, SourceInfoID=None, DeviceInstanceID=2, ModalityID=None, ScanID=None, Modality=None, SOPInstanceUid=None, SOPClassUid=None, PhotometricInterpretation=None, SamplesPerPixel=None, Rows_y=None, Columns_x=None, NrOfFrames=None, SliceThickness=None, ResolutionAxial=None, ResolutionHorizontal=None, ResolutionVertical=None, HorizontalFieldOfView=None, Laterality=None, DICOMModality=None, AnatomicRegion=None, ETDRSField=None, Angiography=None, AcquisitionDateTime=None, PupilDilated=None, DatasetIdentifier=, AltDatasetIdentifier=None, ThumbnailPath=None, OldPath=None, FDAIdentifier=None, Inactive=False, CFROI=None, CFKeypoints=None, CFQuality=None, DateInserted=2026-03-11 11:51:16, DateModified=None, DatePreprocessed=None),
 ImageInstance(ImageInstanceID=81, PublicID=geh39rlz, SeriesID=9, SourceInfoID=None, DeviceInstanceID=2, ModalityID=None, ScanID=None, Modality=None, SOPInstanceUid=None, SOPClassUid=None, PhotometricInterpretation=None, SamplesPerPixel=None, Rows_y=None, Columns_x=None, NrOfFrames=None, SliceThickness=None, ResolutionAxial=None, ResolutionHorizontal=None, ResolutionVertical=None, HorizontalFieldOfView=None, Laterality=None, DICOMModality=None, AnatomicRegion=None, ETDRSField=None, Angiography=None, AcquisitionDateTime=None, PupilDilated=None, DatasetIdentifier=, AltDatasetIdentifier=None, ThumbnailPath=None, OldPath=None, FDAIdentifier=None, Inactive=False, CFROI=None, CFKeypoints=None, CFQuality=None, DateInserted=2026-03-11 11:51:16, DateModified=None, DatePreprocessed=None),
 ImageInstance(ImageInstanceID=52, PublicID=8euo3ruz, SeriesID=6, SourceInfoID=None, DeviceInstanceID=2, ModalityID=None, ScanID=None, Modality=None, SOPInstanceUid=None, SOPClassUid=None, PhotometricInterpretation=None, SamplesPerPixel=None, Rows_y=None, Columns_x=None, NrOfFrames=None, SliceThickness=None, ResolutionAxial=None, ResolutionHorizontal=None, ResolutionVertical=None, HorizontalFieldOfView=None, Laterality=None, DICOMModality=None, AnatomicRegion=None, ETDRSField=None, Angiography=None, AcquisitionDateTime=None, PupilDilated=None, DatasetIdentifier=, AltDatasetIdentifier=None, ThumbnailPath=None, OldPath=None, FDAIdentifier=None, Inactive=False, CFROI=None, CFKeypoints=None, CFQuality=None, DateInserted=2026-03-11 11:51:16, DateModified=None, DatePreprocessed=None),
 ImageInstance(ImageInstanceID=89, PublicID=9w4qgw1p, SeriesID=10, SourceInfoID=None, DeviceInstanceID=2, ModalityID=None, ScanID=None, Modality=None, SOPInstanceUid=None, SOPClassUid=None, PhotometricInterpretation=None, SamplesPerPixel=None, Rows_y=None, Columns_x=None, NrOfFrames=None, SliceThickness=None, ResolutionAxial=None, ResolutionHorizontal=None, ResolutionVertical=None, HorizontalFieldOfView=None, Laterality=None, DICOMModality=None, AnatomicRegion=None, ETDRSField=None, Angiography=None, AcquisitionDateTime=None, PupilDilated=None, DatasetIdentifier=, AltDatasetIdentifier=None, ThumbnailPath=None, OldPath=None, FDAIdentifier=None, Inactive=False, CFROI=None, CFKeypoints=None, CFQuality=None, DateInserted=2026-03-11 11:51:16, DateModified=None, DatePreprocessed=None),
 ImageInstance(ImageInstanceID=58, PublicID=wmzqxqs8, SeriesID=7, SourceInfoID=None, DeviceInstanceID=2, ModalityID=None, ScanID=None, Modality=None, SOPInstanceUid=None, SOPClassUid=None, PhotometricInterpretation=None, SamplesPerPixel=None, Rows_y=None, Columns_x=None, NrOfFrames=None, SliceThickness=None, ResolutionAxial=None, ResolutionHorizontal=None, ResolutionVertical=None, HorizontalFieldOfView=None, Laterality=None, DICOMModality=None, AnatomicRegion=None, ETDRSField=None, Angiography=None, AcquisitionDateTime=None, PupilDilated=None, DatasetIdentifier=, AltDatasetIdentifier=None, ThumbnailPath=None, OldPath=None, FDAIdentifier=None, Inactive=False, CFROI=None, CFKeypoints=None, CFQuality=None, DateInserted=2026-03-11 11:51:16, DateModified=None, DatePreprocessed=None),
 ImageInstance(ImageInstanceID=54, PublicID=8pc2rv4t, SeriesID=6, SourceInfoID=None, DeviceInstanceID=2, ModalityID=None, ScanID=None, Modality=None, SOPInstanceUid=None, SOPClassUid=None, PhotometricInterpretation=None, SamplesPerPixel=None, Rows_y=None, Columns_x=None, NrOfFrames=None, SliceThickness=None, ResolutionAxial=None, ResolutionHorizontal=None, ResolutionVertical=None, HorizontalFieldOfView=None, Laterality=None, DICOMModality=None, AnatomicRegion=None, ETDRSField=None, Angiography=None, AcquisitionDateTime=None, PupilDilated=None, DatasetIdentifier=, AltDatasetIdentifier=None, ThumbnailPath=None, OldPath=None, FDAIdentifier=None, Inactive=False, CFROI=None, CFKeypoints=None, CFQuality=None, DateInserted=2026-03-11 11:51:16, DateModified=None, DatePreprocessed=None),
 ImageInstance(ImageInstanceID=55, PublicID=4r70uru3, SeriesID=6, SourceInfoID=None, DeviceInstanceID=2, ModalityID=None, ScanID=None, Modality=None, SOPInstanceUid=None, SOPClassUid=None, PhotometricInterpretation=None, SamplesPerPixel=None, Rows_y=None, Columns_x=None, NrOfFrames=None, SliceThickness=None, ResolutionAxial=None, ResolutionHorizontal=None, ResolutionVertical=None, HorizontalFieldOfView=None, Laterality=None, DICOMModality=None, AnatomicRegion=None, ETDRSField=None, Angiography=None, AcquisitionDateTime=None, PupilDilated=None, DatasetIdentifier=, AltDatasetIdentifier=None, ThumbnailPath=None, OldPath=None, FDAIdentifier=None, Inactive=False, CFROI=None, CFKeypoints=None, CFQuality=None, DateInserted=2026-03-11 11:51:16, DateModified=None, DatePreprocessed=None),
 ImageInstance(ImageInstanceID=85, PublicID=wsz9ow9r, SeriesID=9, SourceInfoID=None, DeviceInstanceID=2, ModalityID=None, ScanID=None, Modality=None, SOPInstanceUid=None, SOPClassUid=None, PhotometricInterpretation=None, SamplesPerPixel=None, Rows_y=None, Columns_x=None, NrOfFrames=None, SliceThickness=None, ResolutionAxial=None, ResolutionHorizontal=None, ResolutionVertical=None, HorizontalFieldOfView=None, Laterality=None, DICOMModality=None, AnatomicRegion=None, ETDRSField=None, Angiography=None, AcquisitionDateTime=None, PupilDilated=None, DatasetIdentifier=, AltDatasetIdentifier=None, ThumbnailPath=None, OldPath=None, FDAIdentifier=None, Inactive=False, CFROI=None, CFKeypoints=None, CFQuality=None, DateInserted=2026-03-11 11:51:16, DateModified=None, DatePreprocessed=None),
 ImageInstance(ImageInstanceID=88, PublicID=su736kxn, SeriesID=10, SourceInfoID=None, DeviceInstanceID=2, ModalityID=None, ScanID=None, Modality=None, SOPInstanceUid=None, SOPClassUid=None, PhotometricInterpretation=None, SamplesPerPixel=None, Rows_y=None, Columns_x=None, NrOfFrames=None, SliceThickness=None, ResolutionAxial=None, ResolutionHorizontal=None, ResolutionVertical=None, HorizontalFieldOfView=None, Laterality=None, DICOMModality=None, AnatomicRegion=None, ETDRSField=None, Angiography=None, AcquisitionDateTime=None, PupilDilated=None, DatasetIdentifier=, AltDatasetIdentifier=None, ThumbnailPath=None, OldPath=None, FDAIdentifier=None, Inactive=False, CFROI=None, CFKeypoints=None, CFQuality=None, DateInserted=2026-03-11 11:51:16, DateModified=None, DatePreprocessed=None),
 ImageInstance(ImageInstanceID=51, PublicID=iu48bf2i, SeriesID=6, SourceInfoID=None, DeviceInstanceID=2, ModalityID=None, ScanID=None, Modality=None, SOPInstanceUid=None, SOPClassUid=None, PhotometricInterpretation=None, SamplesPerPixel=None, Rows_y=None, Columns_x=None, NrOfFrames=None, SliceThickness=None, ResolutionAxial=None, ResolutionHorizontal=None, ResolutionVertical=None, HorizontalFieldOfView=None, Laterality=None, DICOMModality=None, AnatomicRegion=None, ETDRSField=None, Angiography=None, AcquisitionDateTime=None, PupilDilated=None, DatasetIdentifier=, AltDatasetIdentifier=None, ThumbnailPath=None, OldPath=None, FDAIdentifier=None, Inactive=False, CFROI=None, CFKeypoints=None, CFQuality=None, DateInserted=2026-03-11 11:51:16, DateModified=None, DatePreprocessed=None),
 ImageInstance(ImageInstanceID=63, PublicID=hu2wauch, SeriesID=7, SourceInfoID=None, DeviceInstanceID=2, ModalityID=None, ScanID=None, Modality=None, SOPInstanceUid=None, SOPClassUid=None, PhotometricInterpretation=None, SamplesPerPixel=None, Rows_y=None, Columns_x=None, NrOfFrames=None, SliceThickness=None, ResolutionAxial=None, ResolutionHorizontal=None, ResolutionVertical=None, HorizontalFieldOfView=None, Laterality=None, DICOMModality=None, AnatomicRegion=None, ETDRSField=None, Angiography=None, AcquisitionDateTime=None, PupilDilated=None, DatasetIdentifier=, AltDatasetIdentifier=None, ThumbnailPath=None, OldPath=None, FDAIdentifier=None, Inactive=False, CFROI=None, CFKeypoints=None, CFQuality=None, DateInserted=2026-03-11 11:51:16, DateModified=None, DatePreprocessed=None),
 ImageInstance(ImageInstanceID=87, PublicID=p7668cpf, SeriesID=10, SourceInfoID=None, DeviceInstanceID=2, ModalityID=None, ScanID=None, Modality=None, SOPInstanceUid=None, SOPClassUid=None, PhotometricInterpretation=None, SamplesPerPixel=None, Rows_y=None, Columns_x=None, NrOfFrames=None, SliceThickness=None, ResolutionAxial=None, ResolutionHorizontal=None, ResolutionVertical=None, HorizontalFieldOfView=None, Laterality=None, DICOMModality=None, AnatomicRegion=None, ETDRSField=None, Angiography=None, AcquisitionDateTime=None, PupilDilated=None, DatasetIdentifier=, AltDatasetIdentifier=None, ThumbnailPath=None, OldPath=None, FDAIdentifier=None, Inactive=False, CFROI=None, CFKeypoints=None, CFQuality=None, DateInserted=2026-03-11 11:51:16, DateModified=None, DatePreprocessed=None),

### Inspect Results

The project is now in the DB. We can easily generate a dataframe with image details to inspect results

In [8]:
# inspect the project using the ORM
from eyened_orm import Project

project = Project.by_name(session, 'FAU Fundus Dataset')

In [9]:
project.make_dataframe()

,ImageInstanceID,PublicID,SeriesID,SourceInfoID,DeviceInstanceID,ModalityID,ScanID,Modality,SOPInstanceUid,SOPClassUid,...,ThumbnailPath,OldPath,FDAIdentifier,Inactive,CFROI,CFKeypoints,CFQuality,DateInserted,DateModified,DatePreprocessed
0,46,s0hiq4kt,6,None,2,None,None,None,None,None,...,None,None,None,False,None,None,None,2026-03-11 11:51:16,None,None
1,47,eowkbmct,6,None,2,None,None,None,None,None,...,None,None,None,False,None,None,None,2026-03-11 11:51:16,None,None
2,48,k41kgeyv,6,None,2,None,None,None,None,None,...,None,None,None,False,None,None,None,2026-03-11 11:51:16,None,None
3,49,5qyvlcor,6,None,2,None,None,None,None,None,...,None,None,None,False,None,None,None,2026-03-11 11:51:16,None,None
4,50,ki40y8q4,6,None,2,None,None,None,None,None,...,None,None,None,False,None,None,None,2026-03-11 11:51:16,None,None
5,51,iu48bf2i,6,None,2,None,None,None,None,None,...,None,None,None,False,None,None,None,2026-03-11 11:51:16,None,None
6,52,8euo3ruz,6,None,2,None,None,None,None,None,...,None,None,None,False,None,None,None,2026-03-11 11:51:16,None,None
7,53,krf90y3k,6,None,2,None,None,None,None,None,...,None,None,None,False,None,None,None,2026-03-11 11:51:16,None,None
8,54,8pc2rv4t,6,None,2,None,None,None,None,None,...,None,None,None,False,None,None,None,2026-03-11 11:51:16,None,None
9,55,4r70uru3,6,None,2,None,None,None,None,None,...,None,None,None,False,None,None,None,2026-03-11 11:51:16,None,None
10,56,16w5xxw8,7,None,2,None,None,None,None,None,...,None,None,None,False,None,None,None,2026-03-11 11:51:16,None,None
11,57,j9mxaycb,7,None,2,None,None,None,None,None,...,None,None,None,False,None,None,None,2026-03-11 11:51:16,None,None
12,58,wmzqxqs8,7,None,2,None,None,None,None,None,...,None,None,None,False,None,None,None,2026-03-11 11:51:16,None,None
13,59,tcrnwy1v,7,None,2,None,None,None,None,None,...,None,None,None,False,None,None,None,2026-03-11 11:51:16,None,None
14,60,0ipzuied,7,None,2,None,None,None,None,None,...,None,None,None,False,None,None,None,2026-03-11 11:51:16,None,None
15,61,4my8v6i3,7,None,2,None,None,None,None,None,...,None,None,None,False,None,None,None,2026-03-11 11:51:16,None,None
16,62,ktm7c5sd,7,None,2,None,None,None,None,None,...,None,None,None,False,None,None,None,2026-03-11 11:51:16,None,None
17,63,hu2wauch,7,None,2,None,None,None,None,None,...,None,None,None,False,None,None,None,2026-03-11 11:51:16,None,None
18,64,qybsfi2z,7,None,2,None,None,None,None,None,...,None,None,None,False,None,None,None,2026-03-11 11:51:16,None,None
19,65,fs2x5pmi,7,None,2,None,None,None,None,None,...,None,None,None,False,None,None,None,2026-03-11 11:51:16,None,None
20,66,ogxgtuhb,8,None,2,None,None,None,None,None,...,None,None,None,False,None,None,None,2026-03-11 11:51:16,None,None
21,67,cm4rmvtw,8,None,2,None,None,None,None,None,...,None,None,None,False,None,None,None,2026-03-11 11:51:16,None,None
22,68,xoke4nlw,8,None,2,None,None,None,None,None,...,None,None,None,False,None,None,None,2026-03-11 11:51:16,None,None
23,69,zynmcdin,8,None,2,None,None,None,None,None,...,None,None,None,False,None,None,None,2026-03-11 11:51:16,None,None
24,70,g118eh83,8,None,2,None,None,None,None,None,...,None,None,None,False,None,None,None,2026-03-11 11:51:16,None,None
25,71,ji2o0ms8,8,None,2,None,None,None,None,None,...,None,None,None,False,None,None,None,2026-03-11 11:51:16,None,None
26,72,6eksiky5,8,None,2,None,None,None,None,None,...,None,None,None,False,None,None,None,2026-03-11 11:51:16,None,None
27,73,sb5cancr,8,None,2,None,None,None,None,None,...,None,None,None,False,None,None,None,2026-03-11 11:51:16,None,None
28,74,1y0g5pv4,8,None,2,None,None,None,None,None,...,None,None,None,False,None,None,None,2026-03-11 11:51:16,None,None
29,75,f2sifd6y,8,None,2,None,None,None,None,None,...,None,None,None,False,None,None,None,2026-03-11 11:51:16,None,None
30,76,sd59rms1,9,None,2,None,None,None,None,None,...,None,None,None,False,None,None,None,2026-03-11 11:51:16,None,None
31,77,6z29u67q,9,None,2,None,None,None,None,None,...,None,None,None,False,None,None,None,2026-03-11 11:51:16,None,None
32,78,xu78u8pa,9,None,2,None,None,None,None,None,...,None,None,None,False,None,None,None,2026-03-11 11:51:16,None,None
33,79,zsjq1m7q,9,None,2,None,None,None,None,None,...,None,None,None,False,None,None,None,2026-03-11 11:51:16,None,None
34,80,kkf5ctvp,9,None,2,None,None,None,None,None,...,None,None,None,False,None,None,None,2026-03-11 11:51:16,None,None
35,81,geh39rlz,9,None,2,None,None,None,None,None,...,None,None,None,False,None,None,None,2026-03-11 11:51:16,None,None
36,82,a73gedyj,9,None,2,None,None,None,None,None,...,None,None,None,False,None,None,None,2026-03-11 11:51:16,None,None
37,83,vomytipx,9,None,2,None,None,None,None,None,...,None,None,None,False,None,None,None,2026-03-11 11:51:16,None,None
38,84,qohz8ih1,9,None,2,None,None,None,None,None,...,None,None,None,False,None,None,None,2026-03-11 11:51:16,None,None
39,85,wsz9ow9r,9,None,2,None,None,None,None,None,...,None,None,None,False,None,None,None,2026-03-11 11:51:16,None,None
40,86,xlb1567j,10,None,2,None,None,None,None,None,...,None,None,None,False,None,None,None,2026-03-11 11:51:16,None,None
41,87,p7668cpf,10,None,2,None,None,None,None,None,...,None,None,None,False,None,None,None,2026-03-11 11:51:16,None,None
42,88,su736kxn,10,None,2,None,None,None,None,None,...,None,None,None,False,None,None,None,2026-03-11 11:51:16,None,None
43,89,9w4qgw1p,10,None,2,None,None,None,None,None,...,None,None,None,False,None,None,None,2026-03-11 11:51:16,None,None
44,90,xce3l0et,10,None,2,None,None,None,None,None,...,None,None,None,False,None,None,None,2026-03-11 11:51:16,None,None

In [10]:
raise Exception("Stop here")

Exception: Stop here

### Updating existing projects

Images can be inserted into existing projects, patients, studies and series by passing an existing project name, patient_identifier, study_date or series_id in the input structure. These will be matched to database entities (taking into account their nested structure).

In [ ]:
# to simulate inserting into an existing project, we'll insert the same data again
# use create_patients=False, create_studies=False, create_series=False when inserting into existing objects to ensure that no new objects will be created
# copy_files=True will copy the files to a configurable directory
importer = Importer(
    session=session,
    run_ai_models=True, 
    generate_thumbnails=True,
    # copy_files=True # removed copy_files as it wasn't in __init__ signature I read
)

# Display a summary of what will be imported
import_summary = importer.import_many(data, summary=True)

RuntimeError: Project with name 'FAU Fundus Dataset' not found and create_projects=False

In [ ]:
importer.import_many(data)

100%|██████████| 45/45 [00:00<00:00, 57264.47it/s]

No images to process

[ImageInstance(ImageInstanceID=136, PublicID=a6c6dl5q, SeriesID=106, SourceInfoID=None, DeviceInstanceID=1, ModalityID=None, ScanID=None, Modality=None, SOPInstanceUid=None, SOPClassUid=None, PhotometricInterpretation=None, SamplesPerPixel=None, Rows_y=None, Columns_x=None, NrOfFrames=None, SliceThickness=None, ResolutionAxial=None, ResolutionHorizontal=None, ResolutionVertical=None, HorizontalFieldOfView=None, Laterality=None, DICOMModality=None, AnatomicRegion=None, ETDRSField=None, Angiography=None, AcquisitionDateTime=None, PupilDilated=None, DatasetIdentifier=eyened/public_data/av_segmentation/HRF_AV/images/15_g.jpg, AltDatasetIdentifier=None, ThumbnailPath=, OldPath=None, FDAIdentifier=None, Inactive=False, CFROI=None, CFKeypoints=None, CFQuality=None, DateInserted=2026-03-10 16:48:14, DateModified=2026-03-10 16:48:14, DatePreprocessed=None),
 ImageInstance(ImageInstanceID=137, PublicID=xra9wozv, SeriesID=106, SourceInfoID=None, DeviceInstanceID=1, ModalityID=None, ScanID=None, Modality=None, SOPInstanceUid=None, SOPClassUid=None, PhotometricInterpretation=None, SamplesPerPixel=None, Rows_y=None, Columns_x=None, NrOfFrames=None, SliceThickness=None, ResolutionAxial=None, ResolutionHorizontal=None, ResolutionVertical=None, HorizontalFieldOfView=None, Laterality=None, DICOMModality=None, AnatomicRegion=None, ETDRSField=None, Angiography=None, AcquisitionDateTime=None, PupilDilated=None, DatasetIdentifier=eyened/public_data/av_segmentation/HRF_AV/images/05_h.jpg, AltDatasetIdentifier=None, ThumbnailPath=, OldPath=None, FDAIdentifier=None, Inactive=False, CFROI=None, CFKeypoints=None, CFQuality=None, DateInserted=2026-03-10 16:48:14, DateModified=2026-03-10 16:48:14, DatePreprocessed=None),
 ImageInstance(ImageInstanceID=138, PublicID=ggapy570, SeriesID=106, SourceInfoID=None, DeviceInstanceID=1, ModalityID=None, ScanID=None, Modality=None, SOPInstanceUid=None, SOPClassUid=None, PhotometricInterpretation=None, SamplesPerPixel=None, Rows_y=None, Columns_x=None, NrOfFrames=None, SliceThickness=None, ResolutionAxial=None, ResolutionHorizontal=None, ResolutionVertical=None, HorizontalFieldOfView=None, Laterality=None, DICOMModality=None, AnatomicRegion=None, ETDRSField=None, Angiography=None, AcquisitionDateTime=None, PupilDilated=None, DatasetIdentifier=eyened/public_data/av_segmentation/HRF_AV/images/15_h.jpg, AltDatasetIdentifier=None, ThumbnailPath=, OldPath=None, FDAIdentifier=None, Inactive=False, CFROI=None, CFKeypoints=None, CFQuality=None, DateInserted=2026-03-10 16:48:14, DateModified=2026-03-10 16:48:14, DatePreprocessed=None),
 ImageInstance(ImageInstanceID=139, PublicID=1me2rlvj, SeriesID=106, SourceInfoID=None, DeviceInstanceID=1, ModalityID=None, ScanID=None, Modality=None, SOPInstanceUid=None, SOPClassUid=None, PhotometricInterpretation=None, SamplesPerPixel=None, Rows_y=None, Columns_x=None, NrOfFrames=None, SliceThickness=None, ResolutionAxial=None, ResolutionHorizontal=None, ResolutionVertical=None, HorizontalFieldOfView=None, Laterality=None, DICOMModality=None, AnatomicRegion=None, ETDRSField=None, Angiography=None, AcquisitionDateTime=None, PupilDilated=None, DatasetIdentifier=eyened/public_data/av_segmentation/HRF_AV/images/06_dr.jpg, AltDatasetIdentifier=None, ThumbnailPath=, OldPath=None, FDAIdentifier=None, Inactive=False, CFROI=None, CFKeypoints=None, CFQuality=None, DateInserted=2026-03-10 16:48:14, DateModified=2026-03-10 16:48:14, DatePreprocessed=None),
 ImageInstance(ImageInstanceID=140, PublicID=k2hmrvlb, SeriesID=106, SourceInfoID=None, DeviceInstanceID=1, ModalityID=None, ScanID=None, Modality=None, SOPInstanceUid=None, SOPClassUid=None, PhotometricInterpretation=None, SamplesPerPixel=None, Rows_y=None, Columns_x=None, NrOfFrames=None, SliceThickness=None, ResolutionAxial=None, ResolutionHorizontal=None, ResolutionVertical=None, HorizontalFieldOfView=None, Laterality=None, DICOMModality=None, AnatomicRegion=None, ETDRSField=None, Angiography=None, AcquisitionDateTime=None, PupilDilated=None, DatasetIdentifier=eyened/public_data/av_segmentation/HRF_AV/images/01_dr.jpg, AltDatasetIdentifier=None, ThumbnailPath=, OldPath=None, FDAIdentifier=None, Inactive=False, CFROI=None, CFKeypoints=None, CFQuality=None, DateInserted=2026-03-10 16:48:14, DateModified=2026-03-10 16:48:14, DatePreprocessed=None),
 ImageInstance(ImageInstanceID=141, PublicID=752vqo7p, SeriesID=106, SourceInfoID=None, DeviceInstanceID=1, ModalityID=None, ScanID=None, Modality=None, SOPInstanceUid=None, SOPClassUid=None, PhotometricInterpretation=None, SamplesPerPixel=None, Rows_y=None, Columns_x=None, NrOfFrames=None, SliceThickness=None, ResolutionAxial=None, ResolutionHorizontal=None, ResolutionVertical=None, HorizontalFieldOfView=None, Laterality=None, DICOMModality=None, AnatomicRegion=None, ETDRSField=None, Angiography=None, AcquisitionDateTime=None, PupilDilated=None, DatasetIdentifier=eyened/public_data/av_segmentation/HRF_AV/images/10_g.jpg, AltDatasetIdentifier=None, ThumbnailPath=, OldPath=None, FDAIdentifier=None, Inactive=False, CFROI=None, CFKeypoints=None, CFQuality=None, DateInserted=2026-03-10 16:48:14, DateModified=2026-03-10 16:48:14, DatePreprocessed=None),
 ImageInstance(ImageInstanceID=142, PublicID=7x546ywq, SeriesID=106, SourceInfoID=None, DeviceInstanceID=1, ModalityID=None, ScanID=None, Modality=None, SOPInstanceUid=None, SOPClassUid=None, PhotometricInterpretation=None, SamplesPerPixel=None, Rows_y=None, Columns_x=None, NrOfFrames=None, SliceThickness=None, ResolutionAxial=None, ResolutionHorizontal=None, ResolutionVertical=None, HorizontalFieldOfView=None, Laterality=None, DICOMModality=None, AnatomicRegion=None, ETDRSField=None, Angiography=None, AcquisitionDateTime=None, PupilDilated=None, DatasetIdentifier=eyened/public_data/av_segmentation/HRF_AV/images/12_g.jpg, AltDatasetIdentifier=None, ThumbnailPath=, OldPath=None, FDAIdentifier=None, Inactive=False, CFROI=None, CFKeypoints=None, CFQuality=None, DateInserted=2026-03-10 16:48:14, DateModified=2026-03-10 16:48:14, DatePreprocessed=None),
 ImageInstance(ImageInstanceID=143, PublicID=lf8o3gs8, SeriesID=106, SourceInfoID=None, DeviceInstanceID=1, ModalityID=None, ScanID=None, Modality=None, SOPInstanceUid=None, SOPClassUid=None, PhotometricInterpretation=None, SamplesPerPixel=None, Rows_y=None, Columns_x=None, NrOfFrames=None, SliceThickness=None, ResolutionAxial=None, ResolutionHorizontal=None, ResolutionVertical=None, HorizontalFieldOfView=None, Laterality=None, DICOMModality=None, AnatomicRegion=None, ETDRSField=None, Angiography=None, AcquisitionDateTime=None, PupilDilated=None, DatasetIdentifier=eyened/public_data/av_segmentation/HRF_AV/images/14_dr.JPG, AltDatasetIdentifier=None, ThumbnailPath=, OldPath=None, FDAIdentifier=None, Inactive=False, CFROI=None, CFKeypoints=None, CFQuality=None, DateInserted=2026-03-10 16:48:14, DateModified=2026-03-10 16:48:14, DatePreprocessed=None),
 ImageInstance(ImageInstanceID=144, PublicID=2x7ckhdb, SeriesID=106, SourceInfoID=None, DeviceInstanceID=1, ModalityID=None, ScanID=None, Modality=None, SOPInstanceUid=None, SOPClassUid=None, PhotometricInterpretation=None, SamplesPerPixel=None, Rows_y=None, Columns_x=None, NrOfFrames=None, SliceThickness=None, ResolutionAxial=None, ResolutionHorizontal=None, ResolutionVertical=None, HorizontalFieldOfView=None, Laterality=None, DICOMModality=None, AnatomicRegion=None, ETDRSField=None, Angiography=None, AcquisitionDateTime=None, PupilDilated=None, DatasetIdentifier=eyened/public_data/av_segmentation/HRF_AV/images/15_dr.JPG, AltDatasetIdentifier=None, ThumbnailPath=, OldPath=None, FDAIdentifier=None, Inactive=False, CFROI=None, CFKeypoints=None, CFQuality=None, DateInserted=2026-03-10 16:48:14, DateModified=2026-03-10 16:48:14, DatePreprocessed=None),
 ImageInstance(ImageInstanceID=145, PublicID=j4fyedpq, SeriesID=106, SourceInfoID=None, DeviceInstanceID=1, ModalityID=None, ScanID=None, Modality=None, SOPInstanceUid=None, SOPClassUid=None, PhotometricInterpretation=None, SamplesPerPixel=None, Rows_y=None, Columns_x=None, NrOfFrames=None, SliceThickness=None, ResolutionAxial=None, ResolutionHorizontal=None, ResolutionVertical=None, HorizontalFieldOfView=None, Laterality=None, DICOMModality=None, AnatomicRegion=None, ETDRSField=None, Angiography=None, AcquisitionDateTime=None, PupilDilated=None, DatasetIdentifier=eyened/public_data/av_segmentation/HRF_AV/images/13_g.jpg, AltDatasetIdentifier=None, ThumbnailPath=, OldPath=None, FDAIdentifier=None, Inactive=False, CFROI=None, CFKeypoints=None, CFQuality=None, DateInserted=2026-03-10 16:48:14, DateModified=2026-03-10 16:48:14, DatePreprocessed=None),
 ImageInstance(ImageInstanceID=146, PublicID=r9doujwa, SeriesID=107, SourceInfoID=None, DeviceInstanceID=1, ModalityID=None, ScanID=None, Modality=None, SOPInstanceUid=None, SOPClassUid=None, PhotometricInterpretation=None, SamplesPerPixel=None, Rows_y=None, Columns_x=None, NrOfFrames=None, SliceThickness=None, ResolutionAxial=None, ResolutionHorizontal=None, ResolutionVertical=None, HorizontalFieldOfView=None, Laterality=None, DICOMModality=None, AnatomicRegion=None, ETDRSField=None, Angiography=None, AcquisitionDateTime=None, PupilDilated=None, DatasetIdentifier=eyened/public_data/av_segmentation/HRF_AV/images/06_g.jpg, AltDatasetIdentifier=None, ThumbnailPath=, OldPath=None, FDAIdentifier=None, Inactive=False, CFROI=None, CFKeypoints=None, CFQuality=None, DateInserted=2026-03-10 16:48:14, DateModified=2026-03-10 16:48:14, DatePreprocessed=None),
 ImageInstance(ImageInstanceID=147, PublicID=zvfemdyx, SeriesID=107, SourceInfoID=None, DeviceInstanceID=1, ModalityID=None, ScanID=None, Modality=None, SOPInstanceUid=None, SOPClassUid=None, PhotometricInterpretation=None, SamplesPerPixel=None, Rows_y=None, Columns_x=None, NrOfFrames=None, SliceThickness=None, ResolutionAxial=None, ResolutionHorizontal=None, ResolutionVertical=None, HorizontalFieldOfView=None, Laterality=None, DICOMModality=None, AnatomicRegion=None, ETDRSField=None, Angiography=None, AcquisitionDateTime=None, PupilDilated=None, DatasetIdentifier=eyened/public_data/av_segmentation/HRF_AV/images/04_h.jpg, AltDatasetIdentifier=None, ThumbnailPath=, OldPath=None, FDAIdentifier=None, Inactive=False, CFROI=None, CFKeypoints=None, CFQuality=None, DateInserted=2026-03-10 16:48:14, DateModified=2026-03-10 16:48:14, DatePreprocessed=None),
 ImageInstance(ImageInstanceID=148, PublicID=gmi35q9g, SeriesID=107, SourceInfoID=None, DeviceInstanceID=1, ModalityID=None, ScanID=None, Modality=None, SOPInstanceUid=None, SOPClassUid=None, PhotometricInterpretation=None, SamplesPerPixel=None, Rows_y=None, Columns_x=None, NrOfFrames=None, SliceThickness=None, ResolutionAxial=None, ResolutionHorizontal=None, ResolutionVertical=None, HorizontalFieldOfView=None, Laterality=None, DICOMModality=None, AnatomicRegion=None, ETDRSField=None, Angiography=None, AcquisitionDateTime=None, PupilDilated=None, DatasetIdentifier=eyened/public_data/av_segmentation/HRF_AV/images/14_h.jpg, AltDatasetIdentifier=None, ThumbnailPath=, OldPath=None, FDAIdentifier=None, Inactive=False, CFROI=None, CFKeypoints=None, CFQuality=None, DateInserted=2026-03-10 16:48:14, DateModified=2026-03-10 16:48:14, DatePreprocessed=None),
 ImageInstance(ImageInstanceID=149, PublicID=6pr1l849, SeriesID=107, SourceInfoID=None, DeviceInstanceID=1, ModalityID=None, ScanID=None, Modality=None, SOPInstanceUid=None, SOPClassUid=None, PhotometricInterpretation=None, SamplesPerPixel=None, Rows_y=None, Columns_x=None, NrOfFrames=None, SliceThickness=None, ResolutionAxial=None, ResolutionHorizontal=None, ResolutionVertical=None, HorizontalFieldOfView=None, Laterality=None, DICOMModality=None, AnatomicRegion=None, ETDRSField=None, Angiography=None, AcquisitionDateTime=None, PupilDilated=None, DatasetIdentifier=eyened/public_data/av_segmentation/HRF_AV/images/09_h.jpg, AltDatasetIdentifier=None, ThumbnailPath=, OldPath=None, FDAIdentifier=None, Inactive=False, CFROI=None, CFKeypoints=None, CFQuality=None, DateInserted=2026-03-10 16:48:14, DateModified=2026-03-10 16:48:14, DatePreprocessed=None),
 ImageInstance(ImageInstanceID=150, PublicID=bnz05e3r, SeriesID=107, SourceInfoID=None, DeviceInstanceID=1, ModalityID=None, ScanID=None, Modality=None, SOPInstanceUid=None, SOPClassUid=None, PhotometricInterpretation=None, SamplesPerPixel=None, Rows_y=None, Columns_x=None, NrOfFrames=None, SliceThickness=None, ResolutionAxial=None, ResolutionHorizontal=None, ResolutionVertical=None, HorizontalFieldOfView=None, Laterality=None, DICOMModality=None, AnatomicRegion=None, ETDRSField=None, Angiography=None, AcquisitionDateTime=None, PupilDilated=None, DatasetIdentifier=eyened/public_data/av_segmentation/HRF_AV/images/02_h.jpg, AltDatasetIdentifier=None, ThumbnailPath=, OldPath=None, FDAIdentifier=None, Inactive=False, CFROI=None, CFKeypoints=None, CFQuality=None, DateInserted=2026-03-10 16:48:14, DateModified=2026-03-10 16:48:14, DatePreprocessed=None),
 ImageInstance(ImageInstanceID=151, PublicID=fja793j3, SeriesID=107, SourceInfoID=None, DeviceInstanceID=1, ModalityID=None, ScanID=None, Modality=None, SOPInstanceUid=None, SOPClassUid=None, PhotometricInterpretation=None, SamplesPerPixel=None, Rows_y=None, Columns_x=None, NrOfFrames=None, SliceThickness=None, ResolutionAxial=None, ResolutionHorizontal=None, ResolutionVertical=None, HorizontalFieldOfView=None, Laterality=None, DICOMModality=None, AnatomicRegion=None, ETDRSField=None, Angiography=None, AcquisitionDateTime=None, PupilDilated=None, DatasetIdentifier=eyened/public_data/av_segmentation/HRF_AV/images/08_h.jpg, AltDatasetIdentifier=None, ThumbnailPath=, OldPath=None, FDAIdentifier=None, Inactive=False, CFROI=None, CFKeypoints=None, CFQuality=None, DateInserted=2026-03-10 16:48:14, DateModified=2026-03-10 16:48:14, DatePreprocessed=None),
 ImageInstance(ImageInstanceID=152, PublicID=roe4fwez, SeriesID=107, SourceInfoID=None, DeviceInstanceID=1, ModalityID=None, ScanID=None, Modality=None, SOPInstanceUid=None, SOPClassUid=None, PhotometricInterpretation=None, SamplesPerPixel=None, Rows_y=None, Columns_x=None, NrOfFrames=None, SliceThickness=None, ResolutionAxial=None, ResolutionHorizontal=None, ResolutionVertical=None, HorizontalFieldOfView=None, Laterality=None, DICOMModality=None, AnatomicRegion=None, ETDRSField=None, Angiography=None, AcquisitionDateTime=None, PupilDilated=None, DatasetIdentifier=eyened/public_data/av_segmentation/HRF_AV/images/03_h.jpg, AltDatasetIdentifier=None, ThumbnailPath=, OldPath=None, FDAIdentifier=None, Inactive=False, CFROI=None, CFKeypoints=None, CFQuality=None, DateInserted=2026-03-10 16:48:14, DateModified=2026-03-10 16:48:14, DatePreprocessed=None),
 ImageInstance(ImageInstanceID=153, PublicID=l7lpelz6, SeriesID=107, SourceInfoID=None, DeviceInstanceID=1, ModalityID=None, ScanID=None, Modality=None, SOPInstanceUid=None, SOPClassUid=None, PhotometricInterpretation=None, SamplesPerPixel=None, Rows_y=None, Columns_x=None, NrOfFrames=None, SliceThickness=None, ResolutionAxial=None, ResolutionHorizontal=None, ResolutionVertical=None, HorizontalFieldOfView=None, Laterality=None, DICOMModality=None, AnatomicRegion=None, ETDRSField=None, Angiography=None, AcquisitionDateTime=None, PupilDilated=None, DatasetIdentifier=eyened/public_data/av_segmentation/HRF_AV/images/05_dr.jpg, AltDatasetIdentifier=None, ThumbnailPath=, OldPath=None, FDAIdentifier=None, Inactive=False, CFROI=None, CFKeypoints=None, CFQuality=None, DateInserted=2026-03-10 16:48:14, DateModified=2026-03-10 16:48:14, DatePreprocessed=None),
 ImageInstance(ImageInstanceID=154, PublicID=feqf7xpq, SeriesID=107, SourceInfoID=None, DeviceInstanceID=1, ModalityID=None, ScanID=None, Modality=None, SOPInstanceUid=None, SOPClassUid=None, PhotometricInterpretation=None, SamplesPerPixel=None, Rows_y=None, Columns_x=None, NrOfFrames=None, SliceThickness=None, ResolutionAxial=None, ResolutionHorizontal=None, ResolutionVertical=None, HorizontalFieldOfView=None, Laterality=None, DICOMModality=None, AnatomicRegion=None, ETDRSField=None, Angiography=None, AcquisitionDateTime=None, PupilDilated=None, DatasetIdentifier=eyened/public_data/av_segmentation/HRF_AV/images/10_dr.JPG, AltDatasetIdentifier=None, ThumbnailPath=, OldPath=None, FDAIdentifier=None, Inactive=False, CFROI=None, CFKeypoints=None, CFQuality=None, DateInserted=2026-03-10 16:48:14, DateModified=2026-03-10 16:48:14, DatePreprocessed=None),
 ImageInstance(ImageInstanceID=155, PublicID=z1amiy74, SeriesID=107, SourceInfoID=None, DeviceInstanceID=1, ModalityID=None, ScanID=None, Modality=None, SOPInstanceUid=None, SOPClassUid=None, PhotometricInterpretation=None, SamplesPerPixel=None, Rows_y=None, Columns_x=None, NrOfFrames=None, SliceThickness=None, ResolutionAxial=None, ResolutionHorizontal=None, ResolutionVertical=None, HorizontalFieldOfView=None, Laterality=None, DICOMModality=None, AnatomicRegion=None, ETDRSField=None, Angiography=None, AcquisitionDateTime=None, PupilDilated=None, DatasetIdentifier=eyened/public_data/av_segmentation/HRF_AV/images/11_g.jpg, AltDatasetIdentifier=None, ThumbnailPath=, OldPath=None, FDAIdentifier=None, Inactive=False, CFROI=None, CFKeypoints=None, CFQuality=None, DateInserted=2026-03-10 16:48:14, DateModified=2026-03-10 16:48:14, DatePreprocessed=None),
 ImageInstance(ImageInstanceID=156, PublicID=u5pok654, SeriesID=108, SourceInfoID=None, DeviceInstanceID=1, ModalityID=None, ScanID=None, Modality=None, SOPInstanceUid=None, SOPClassUid=None, PhotometricInterpretation=None, SamplesPerPixel=None, Rows_y=None, Columns_x=None, NrOfFrames=None, SliceThickness=None, ResolutionAxial=None, ResolutionHorizontal=None, ResolutionVertical=None, HorizontalFieldOfView=None, Laterality=None, DICOMModality=None, AnatomicRegion=None, ETDRSField=None, Angiography=None, AcquisitionDateTime=None, PupilDilated=None, DatasetIdentifier=eyened/public_data/av_segmentation/HRF_AV/images/03_g.jpg, AltDatasetIdentifier=None, ThumbnailPath=, OldPath=None, FDAIdentifier=None, Inactive=False, CFROI=None, CFKeypoints=None, CFQuality=None, DateInserted=2026-03-10 16:48:14, DateModified=2026-03-10 16:48:14, DatePreprocessed=None),
 ImageInstance(ImageInstanceID=157, PublicID=g80b8mtw, SeriesID=108, SourceInfoID=None, DeviceInstanceID=1, ModalityID=None, ScanID=None, Modality=None, SOPInstanceUid=None, SOPClassUid=None, PhotometricInterpretation=None, SamplesPerPixel=None, Rows_y=None, Columns_x=None, NrOfFrames=None, SliceThickness=None, ResolutionAxial=None, ResolutionHorizontal=None, ResolutionVertical=None, HorizontalFieldOfView=None, Laterality=None, DICOMModality=None, AnatomicRegion=None, ETDRSField=None, Angiography=None, AcquisitionDateTime=None, PupilDilated=None, DatasetIdentifier=eyened/public_data/av_segmentation/HRF_AV/images/10_h.jpg, AltDatasetIdentifier=None, ThumbnailPath=, OldPath=None, FDAIdentifier=None, Inactive=False, CFROI=None, CFKeypoints=None, CFQuality=None, DateInserted=2026-03-10 16:48:14, DateModified=2026-03-10 16:48:14, DatePreprocessed=None),
 ImageInstance(ImageInstanceID=158, PublicID=ihmhv73a, SeriesID=108, SourceInfoID=None, DeviceInstanceID=1, ModalityID=None, ScanID=None, Modality=None, SOPInstanceUid=None, SOPClassUid=None, PhotometricInterpretation=None, SamplesPerPixel=None, Rows_y=None, Columns_x=None, NrOfFrames=None, SliceThickness=None, ResolutionAxial=None, ResolutionHorizontal=None, ResolutionVertical=None, HorizontalFieldOfView=None, Laterality=None, DICOMModality=None, AnatomicRegion=None, ETDRSField=None, Angiography=None, AcquisitionDateTime=None, PupilDilated=None, DatasetIdentifier=eyened/public_data/av_segmentation/HRF_AV/images/01_h.jpg, AltDatasetIdentifier=None, ThumbnailPath=, OldPath=None, FDAIdentifier=None, Inactive=False, CFROI=None, CFKeypoints=None, CFQuality=None, DateInserted=2026-03-10 16:48:14, DateModified=2026-03-10 16:48:14, DatePreprocessed=None),

In [ ]:
project = Project.by_name(session, 'FAU Fundus Dataset')
project.make_dataframe()

,ImageInstanceID,PublicID,SeriesID,SourceInfoID,DeviceInstanceID,ModalityID,ScanID,Modality,SOPInstanceUid,SOPClassUid,...,ThumbnailPath,OldPath,FDAIdentifier,Inactive,CFROI,CFKeypoints,CFQuality,DateInserted,DateModified,DatePreprocessed
0,91,texke9in,96,None,1,None,None,None,None,None,...,,None,None,False,None,None,None,2026-03-10 16:47:22,2026-03-10 16:47:22,None
1,92,oepw2871,96,None,1,None,None,None,None,None,...,,None,None,False,None,None,None,2026-03-10 16:47:22,2026-03-10 16:47:22,None
2,93,a4ngali0,96,None,1,None,None,None,None,None,...,,None,None,False,None,None,None,2026-03-10 16:47:22,2026-03-10 16:47:22,None
3,94,w5nm1ell,96,None,1,None,None,None,None,None,...,,None,None,False,None,None,None,2026-03-10 16:47:22,2026-03-10 16:47:22,None
4,95,41aqx44d,96,None,1,None,None,None,None,None,...,,None,None,False,None,None,None,2026-03-10 16:47:22,2026-03-10 16:47:22,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,176,6fq7nldz,110,None,1,None,None,None,None,None,...,,None,None,False,None,None,None,2026-03-10 16:48:14,2026-03-10 16:48:14,None
86,177,lza6yjo8,110,None,1,None,None,None,None,None,...,,None,None,False,None,None,None,2026-03-10 16:48:14,2026-03-10 16:48:14,None
87,178,vfn8fzmz,110,None,1,None,None,None,None,None,...,,None,None,False,None,None,None,2026-03-10 16:48:14,2026-03-10 16:48:14,None
88,179,z188pzxm,110,None,1,None,None,None,None,None,...,,None,None,False,None,None,None,2026-03-10 16:48:14,2026-03-10 16:48:14,None
89,180,vj4xir1u,110,None,1,None,None,None,None,None,...,,None,None,False,None,None,None,2026-03-10 16:48:14,2026-03-10 16:48:14,None